#!/usr/bin/env python3
"""
Generates the Root PORTFOLIO_README.md and compiles comprehensive data structures
for the React web dashboard in /src/data/projectsData.ts.
"""

import os
import json
import csv

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECTS_DIR = os.path.join(REPO_ROOT, "projects")

# 1. Root PORTFOLIO_README.md
portfolio_readme = """# Farjad Zeya — Data Analyst Portfolio
**Email:** [farjadzeya1234@gmail.com](mailto:farjadzeya1234@gmail.com) | **Phone:** +91 6204812301 | **Location:** New Delhi, India  
**Specialization:** Python (pandas, NumPy) • SQL (MySQL) • Microsoft Excel • Power BI • Business Intelligence • MIS Reporting

---

## 👨‍💻 Professional Summary
Results-oriented Data Analyst with a B.Tech in Computer Science (Jamia Hamdard, 2026) and hands-on experience across the entire data lifecycle — data extraction, cleaning, exploratory data analysis (EDA), statistical evaluation, KPI dashboarding, and stakeholder reporting. Currently working as a **Maintenance Data Analyst at CK Infrastructure Ltd**, maintaining diesel consumption databases and delivering Excel/Pivot Table MIS reports to management. Previously completed a Data Analyst Internship at **Cochain LLC** conducting Python EDA and machine learning evaluation.

This portfolio repository houses **four production-quality, end-to-end data analytics projects** designed to solve mission-critical business problems across E-Commerce, Retail Banking, Supply Chain Logistics, and Digital Marketing.

---

## 🛠️ Technical Skills Matrix

| Category | Competencies & Tools |
| :--- | :--- |
| **Data Analysis & EDA** | Python (`pandas`, `NumPy`, `Matplotlib`), SQL, Exploratory Data Analysis, Descriptive Statistics, Trend Analysis, RFM Analysis, Churn & Funnel Analysis |
| **Databases & Querying** | MySQL, Relational Database Design, Complex `JOIN`s, Subqueries, Common Table Expressions (CTEs), Window Functions (`NTILE`, `LAG`, `LEAD`, `DENSE_RANK`, `SUM OVER`) |
| **Reporting & Dashboards** | Microsoft Power BI (Star Schema, DAX Calculated Measures, Time Intelligence, Slicers), Excel Pivot Tables & Charts, MIS Executive Reporting |
| **Data Quality & Pipeline** | Data Cleaning, Missing Value Imputation, Deduplication, Data Integrity Enforcement, Feature Engineering, Outlier Treatment |
| **Developer Tools** | Git, GitHub, VS Code, Jupyter Notebook, Streamlit, Linux CLI |

---

## 📂 Featured Portfolio Projects

### [Project 1: E-Commerce Customer & Sales Analytics](./projects/01-ecommerce-customer-sales-analytics/)
* **Technologies:** SQL (MySQL), Python (pandas, NumPy, Matplotlib), Power BI, Streamlit
* **Core Objective:** Analyzed sales, profit margins, customer cohorts, product categories, and geographic regions to optimize pricing and discount governance.
* **Key Technical Deliverables:**
  - Ingested and cleaned ~2,100 multi-region raw transactions with missing discounts and anomalous formatting.
  - Implemented **RFM (Recency, Frequency, Monetary) customer segmentation** using MySQL CTEs and Python quantiles.
  - Built an interactive **Power BI KPI Dashboard** with dynamic DAX time-intelligence formulas (YoY, MoM growth).
  - Proved Pareto 80/20 distribution: 38% of revenue generated by top 14% "Champions" cohort.
* **Repository Link:** [View Project 1 Directory](./projects/01-ecommerce-customer-sales-analytics/)

---

### [Project 2: Banking Customer Churn & Retention Analysis](./projects/02-banking-customer-churn-retention/)
* **Technologies:** SQL (MySQL), Python (pandas, NumPy, Matplotlib), Power BI, Streamlit
* **Core Objective:** Measured customer attrition rate (20.4%) across 2,500 retail banking accounts and evaluated behavioral churn drivers to safeguard $48M+ in deposits.
* **Key Technical Deliverables:**
  - Evaluated multi-dimensional churn drivers across tenure cohorts, digital activity, and account balance brackets.
  - Uncovered the **Multi-Product Paradox**: clients with 2 products achieve optimal retention (8.1% churn), whereas clients with 3-4 products experience >78% churn.
  - Engineered a composite **Retention Risk Tier** model ("High Risk", "Medium Risk", "Low Risk") in Python & SQL.
  - Created a Power BI Retention Cockpit prioritizing at-risk high-balance depositors for relationship management intervention.
* **Repository Link:** [View Project 2 Directory](./projects/02-banking-customer-churn-retention/)

---

### [Project 3: Supply Chain & Delivery Performance Analytics](./projects/03-supply-chain-delivery-analytics/)
* **Technologies:** SQL (MySQL), Microsoft Excel (Advanced Pivot Tables, MIS Reporting), Power BI
* **Core Objective:** Analyzed on-time delivery (OTD %), dispatch delays, supplier reliability, and freight cost per KG across 2,200 consignments to identify fulfillment bottlenecks.
* **Key Technical Deliverables:**
  - Evaluated network-wide On-Time Delivery Rate (81.4%) and average delay durations (3.4 days).
  - Built a comprehensive **Supplier Performance Scorecard** tracking OTD %, defect/damage frequency, and freight volume.
  - Mapped a **Route Bottleneck Matrix** using SQL window functions (`DENSE_RANK()`), identifying severe dispatch latency at Kolkata Gateway Hub (WH-KOL-04).
  - Designed an Excel MIS reporting model with dynamic `XLOOKUP`, `SUMIFS`, `AVERAGEIF`, and conditional formatting.
* **Repository Link:** [View Project 3 Directory](./projects/03-supply-chain-delivery-analytics/)

---

### [Project 4: Marketing Campaign & Customer Conversion Analytics](./projects/04-marketing-campaign-conversion-analytics/)
* **Technologies:** SQL (MySQL), Python (pandas, NumPy, Matplotlib), Power BI, Streamlit
* **Core Objective:** Evaluated campaign ROI, Customer Acquisition Cost (CAC), and channel performance across 3,500 inbound leads and 10 digital campaigns.
* **Key Technical Deliverables:**
  - Mapped a full 6-stage **lead-to-customer conversion funnel** (Lead ➔ MQL ➔ SQL ➔ Opportunity ➔ Closed-Won) and pinpointed a 42% drop-off at the MQL-to-SQL handoff.
  - Calculated channel-level unit economics: LinkedIn Ads delivered highest enterprise deal sizes ($24.5k) and 7.2x ROAS; Email delivered 1,240% net ROI; Influencer marketing proved unprofitable (0.82x ROAS).
  - Designed interactive Power BI and Streamlit dashboards featuring conversion drop-off charts and budget allocation matrices.
* **Repository Link:** [View Project 4 Directory](./projects/04-marketing-campaign-conversion-analytics/)

---

## 🚀 How to Set Up & Run Any Project Locally

Each project is self-contained with its own datasets, scripts, SQL schemas, and interactive apps:

```bash
# Example: Running Project 1
cd projects/01-ecommerce-customer-sales-analytics

# 1. Set up a virtual environment
python -m venv .venv
source .venv/bin/activate  # On Windows: .venv\\Scripts\\activate

# 2. Install dependencies
pip install -r requirements.txt

# 3. Execute the data cleaning and analysis pipeline
python src/data_cleaning.py
python src/analysis.py

# 4. Launch the interactive dashboard
streamlit run streamlit_app.py
```

---

## 📬 Contact & Portfolio Inquiries
- **Farjad Zeya**
- **Email:** [farjadzeya1234@gmail.com](mailto:farjadzeya1234@gmail.com)
- **Phone:** +91 6204812301
- **Target Roles:** Data Analyst • MIS Analyst • Reporting Analyst • Business Intelligence Analyst
"""

with open(os.path.join(REPO_ROOT, "PORTFOLIO_README.md"), "w", encoding="utf-8") as f:
    f.write(portfolio_readme)

print("Created PORTFOLIO_README.md successfully.")
